manateefood/app/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

# admin.autodiscover()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('main.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^houses/', include('houses.urls')),
]

manateefood/houses/urls.py
from django.conf.urls import url
from . import views

app_name = 'houses'

urlpatterns = [
    url(r'^$', views.all_houses, name="all_houses"),
    url(r'^admin/$', views.admin_show_houses, name="admin_show_houses"),
    url(r'^create/$', views.create_house, name="create_house"),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit_house, name="edit_house"),
    url(r'^(?P<pk>[0-9]+)/supplies/$', views.show_supplies, name="show_supplies"),
]

manateefood/houses/models.py
from datetime import date

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from users.models import ManateeFoodUser

# Create your models here.

class House(models.Model):
    """A top-level entity containing members, supplies, meals and products"""
    name = models.CharField(_("House name"), max_length=30, blank=False)

    members = models.ManyToManyField(ManateeFoodUser, related_name="houses")

    created_at = models.DateTimeField(_("House created at"), auto_now=True)
    updated_at = models.DateTimeField(_("House updated at"), auto_now=True)
    is_active = models.BooleanField(_("House is active"), default=True)


class Supply(models.Model):
    """
    Represents a supply with a shopping date, amount and supplier
    (person that bought the supply). Happens in the context of a House.
    """
    amount = models.IntegerField(_("Supply amount"), help_text=_("Supply amount (CHF cents)"))
    shopping_date = models.DateField(_("Supply shopping date"), default=date.today)

    supplier = models.ForeignKey(ManateeFoodUser, on_delete=models.CASCADE)
    house = models.ForeignKey(House, on_delete=models.CASCADE)

    created_at = models.DateTimeField(_("Supply created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Supply updated at"), auto_now=True)
    is_active = models.BooleanField(_("Supply is active"), default=True)

class Meal(models.Model):
    """
    Represents a meal in time, with products consumed (MealProductConsumption),
    and users that participate to that meal (MealUserParticipation).
    Happens in the context of a House.
    """
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    datetime = models.DateTimeField(_("Meal approximate date and time"), default=timezone.now)

    created_at = models.DateTimeField(_("Meal created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Meal updated at"), auto_now=True)
    is_active = models.BooleanField(_("Meal is active"), default=True)

class MealProductConsumption(models.Model):
    """Represents a consumption of a product with an amount. Part of a meal."""
    amount = models.DecimalField(_("Amount of product consumed"), max_digits=6, decimal_places=2, default=0)

    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE)

class MealUserParticipation(models.Model):
    """Represents the participation of a user with a factor. Part of a meal."""
    participation_factor = models.IntegerField(_("Participation factor"), default=0)

    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    participant = models.ForeignKey(ManateeFoodUser, on_delete=models.CASCADE)

manateefood/houses/forms.py
from django.forms import ModelForm

from .models import House, Supply


class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = ['name', 'members']

class SupplyForm(ModelForm):
    class Meta:
        model = Supply
        fields = ['amount', 'shopping_date', 'supplier']

manateefood/houses/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from app.decorators import superuser_required
from users.models import ManateeFoodUser
from .models import House, Supply
from .forms import HouseForm

# Create your views here.

@login_required
def all_houses(request):
    upk = request.user.pk
    user = ManateeFoodUser.objects.get(pk=upk)
    houses = user.houses.all()

    return render(request, 'houses/all_houses.html', {'houses': houses})

@superuser_required
def admin_show_houses(request):
    houses = House.objects.all()

    return render(request, 'houses/all_houses.html', {'houses': houses})

def create_house(request):
    # After edit
    if request.method == "POST":
        form = HouseForm(request.POST)

        if form.is_valid():
            new_house = form.save()
    # Before edit
    else:
        form = HouseForm()

    #TODO: use a specific create_house template for house creation
    return render(request, 'houses/edit_house.html', {'form':form})


def edit_house(request, pk):
    house = get_object_or_404(House, pk=pk, is_active=True)

    # After edit
    if request.method == "POST":
        form = HouseForm(request.POST, instance=house)

        if form.is_valid():
            new_house = form.save()
    # Before edit
    else:
        form = HouseForm(instance=house)

    return render(request, 'houses/edit_house.html', {'form':form})

def show_supplies(request, pk):
    house = get_object_or_404(House, pk=pk, is_active=True)
    supplies = Supply.objects.filter(pk=pk)

    return render(request, 'houses/show_supplies.html', {'house': house, 'supplies': supplies})

manateefood/houses/templates/houses/all_houses.html
{% extends "base.html" %}

{% load i18n static %}

{% block title %}{% trans "Home" %} - {{ block.super }}{% endblock %}

{% block content %}

    <h3>{% trans 'All houses' %}</h3>

    <table>
        <tr>
            <th>{% trans 'Name' %}</th>
            <th>{% trans 'Members' %}</th>
        </tr>

        {% for house in houses %}
            <tr>
                <td>
                    <a href="{% url 'houses:edit_house' house.pk %}">
                        {{ house.name }}
                    </a>
                </td>
                <td>
                    {% for member in house.members.all %}
                        {{ member }}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

{% block js %}

{% endblock %}

manateefood/houses/templates/houses/edit_house.html
{% extends "base.html" %}

{% load i18n static %}

{% block title %}{% trans "Home" %} - {{ block.super }}{% endblock %}

{% block content %}

    <h3>{% trans 'Edit house' %}</h3>

    <form method="POST" action="#">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="{% trans 'Submit' %}">
    </form>

{% endblock %}

{% block js %}

{% endblock %}

manateefood/houses/templates/houses/show_supplies.html
{% extends "base.html" %}

{% load i18n static %}

{% block title %}{% trans "Home" %} - {{ block.super }}{% endblock %}

{% block content %}

    <h3>{% trans 'Supplies for house ' %}{{ house.name }}</h3>

    <table>
        <tr>
            <th>{% trans 'Amount' %}</th>
            <th>{% trans 'Supplier' %}</th>
            <th>{% trans 'Shopping date' %}</th>
        </tr>

        {% for supply in supplies %}
            <tr>
                <td>
                    {{ supply.amount }}
                </td>
                <td>
                    {{ supply.supplier }}
                </td>
                <td>
                    {{ supply.shopping_date }}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

{% block js %}

{% endblock %}