manateefood/app/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

# admin.autodiscover()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('main.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^houses/', include('houses.urls')),
]

manateefood/houses/urls.py
from django.conf.urls import url
from . import views

app_name = 'houses'

urlpatterns = [
    url(r'^$', views.all_houses, name="all_houses"),
    url(r'^admin/$', views.admin_show_houses, name="admin_show_houses"),
    url(r'^create/$', views.create_house, name="create_house"),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit_house, name="edit_house"),
    url(r'^(?P<pk>[0-9]+)/supplies/$', views.show_supplies, name="show_supplies"),
]

manateefood/main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.home, name="home"),
]

manateefood/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    url('^login/$', views.login, name="login"),
    url('^register/$', views.register, name="register"),
    url('^logout/$', views.logout, name="logout"),
]

manateefood/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="title" content="{% trans 'Title' %}">
        <meta name="description" content="{% trans 'Description' %}">
        <meta name="keywords" content="{% trans 'Keywords' %}">
        <meta name="author" content="CookZattol" />

        <!-- Stylesheets
        ============================================= -->
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">

        <link rel="stylesheet" href="{% static 'css/custom.css' %}">


        <!-- Document Title
        ============================================= -->
        <title>{% block title %}{% trans "Manateefood" %}{% endblock %}</title>

    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="{% url 'main:home' %}">
                {% trans 'Manateefood' %}
            </a>
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsDefault"
                aria-controls="navbarsDefault" aria-expanded="false" aria-label="{% trans 'Toggle Navigation' %}">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsDefault">
                <ul class="navbar-nav mr-auto">
                    {% block nav_list %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'main:home' %}">{% trans 'Home' %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">{% trans 'Add Meal' %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">{% trans 'Supply' %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'houses:all_houses' %}">{% trans 'Houses' %}</a>
                        </li>
                    {% endblock %}
                </ul>
                <div class="mt-2 mt-md-0">
                    {% if user.is_authenticated %}
                        <span class="text-white">{{user}} - </span><a href="{% url 'users:logout' %}"><i class="fa fa-unlock" aria-hidden="true"></i>&nbsp{% trans 'Logout' %}</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'users:login' %}"><i class="fa fa-lock" aria-hidden="true"></i> {% trans 'Login' %}</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="container-fluid h-100">
            {% block content %}
            {% endblock %}
        </div>

            <!-- JavaScripts
            ============================================= -->

            <script type="text/javascript" src="{% static 'jquery/dist/jquery.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'popper.js/dist/umd/popper.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'toastr/toastr.min.js' %}"></script>

            <script type="text/javascript">
                //Toastr Options
                toastr.options = {
                    "closeButton": true,
                    "progressBar": true,
                    "fadeIn": 300,
                    "timeOut": 3500,
                    "fadeOut": 600,
                    "preventDuplicates": true,               
                };

                {% for message in messages %}
                    toastr.{% if message.tags %}{{ message.tags }}{% else %}info{% endif %}("{{ message|escapejs }}");
                {% endfor %}


            </script>

            {% block js %}
            {% endblock %}

    </body>
</html>